name: Check CS
on:
    push:
        branches:
            - master
    pull_request_target:

jobs:
    build:
        runs-on: ubuntu-latest
        name: Check code style
        steps:
            -   uses: actions/checkout@v2
                with:
                    fetch-depth: 10

            -   name: Install PHP
                uses: shivammathur/setup-php@v2
                with:
                    coverage: none
                    php-version: "8.1"
                    tools: cs2pr

            -   name: Cache dependencies installed with composer
                uses: actions/cache@13aacd865c20de90d75de3b17ebe84f7a17d57d2 # v4
                with:
                    path: "~/.composer/cache"
                    key: php-${{ matrix.php-version }}-composer-locked-${{ hashFiles('composer.lock') }}
                    restore-keys: php-${{ matrix.php-version }}-composer-locked-

            -   name: Install dependencies with composer
                run: composer update --no-interaction --no-progress --no-suggest

            -   name: Run CS checks
                run: composer cscheck
