name: PHPStan

on:
    push:
        branches:
            - master
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest
        name: Static analysis
        steps:
            -   uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

            -   name: Install PHP
                uses: shivammathur/setup-php@v2
                with:
                    coverage: none
                    php-version: "8.4"
                    tools: cs2pr

            -   name: Cache dependencies installed with composer
                uses: actions/cache@v4
                with:
                    path: "~/.composer/cache"
                    key: php-8.4-composer-locked-${{ hashFiles('composer.lock') }}
                    restore-keys: php-8.4-composer-locked-

            -   name: Install dependencies with composer
                run: composer update --no-progress --no-interaction --prefer-dist

            -   name: Run PHPStan
                run: composer phpstan --error-format=checkstyle
