name: PHPStan

on:
    push:
        branches:
            - master
    pull_request_target:

jobs:
    build:
        runs-on: ubuntu-latest
        name: Static analysis
        steps:
            -   uses: actions/checkout@v2

            -   name: Install PHP
                uses: shivammathur/setup-php@v2
                with:
                    coverage: none
                    php-version: "8.2"
                    tools: cs2pr

            -   name: Cache dependencies installed with composer
                uses: actions/cache@v1
                with:
                    path: "~/.composer/cache"
                    key: php-${{ matrix.php-version }}-composer-locked-${{ hashFiles('composer.lock') }}
                    restore-keys: php-${{ matrix.php-version }}-composer-locked-

            -   name: Install dependencies with composer
                run: composer update --no-progress --no-suggest --no-interaction --prefer-dist

            -   name: Run PHPStan
                run: composer phpstan --error-format=checkstyle
